apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        env:
        - name: SQL_PASSWORD
          value: <replaceme>
        - name: SQL_SERVER
          value: <replaceme>
        - name: SQL_USER
          value: <replaceme>
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: SQL_DBNAME
          value: mydrivingDB
        - name: OPENAPI_DOCS_URI
          value: http://changeme 
        image: registryyme7268.azurecr.io/tripinsights/userprofile:1.0
        ports: 
        - containerPort: 80
        readinessProbe: # is the container ready to receive traffic?
          httpGet:
            port: 80
            path: /api/user/healthcheck
        livenessProbe: # is the container healthy?
          httpGet:
            port: 80
            path: /api/user/healthcheck