apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: registryyme7268.azurecr.io/tripinsights/poi:1.0
        ports: 
        - containerPort: 80
        readinessProbe: 
          initialDelaySeconds: 10
          httpGet:
            port: 80
            path: /api/poi/healthcheck
        livenessProbe: 
          initialDelaySeconds: 10
          httpGet:
            port: 80
            path: /api/poi/healthcheck
        volumeMounts:
        - mountPath: /secrets
          name: secrets-store-inline
          readOnly: true
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname
        name: secrets-store-inline