apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
        aadpodidbinding: azure-pod-identity-binding-selector
    spec:
      containers:
      - name: trips
        image: registryyme7268.azurecr.io/tripinsights/trips:1.0
        ports: 
        - containerPort: 80
        readinessProbe: # is the container ready to receive traffic?
          httpGet:
            port: 80
            path: /api/trips/healthcheck
        livenessProbe: # is the container healthy?
          httpGet:
            port: 80
            path: /api/trips/healthcheck

        volumeMounts:
           - name: secrets-store-inline
             mountPath: "/secrets"
             readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname         
---       
apiVersion: v1         
kind: Service
metadata:
  namespace: api
  name: trips
spec:
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 80
  type: ClusterIP
